import { Metadata } from 'next';
import React from 'react'

// export const metadata: Metadata = {
//   // اینجا اون بالای صفحه اسمشو تغییر میده
//   title: "Aboute Page",
//   description: "Generated by create next app",
// };

// advance use metaData
export const metadata: Metadata = {
  // اینجا اون بالای صفحه اسمشو تغییر میده
  title: {
    // اینجا مثلا میخوام یک مقداری رو درنظر نگیریم
    absolute:"kkk",
    default:"shopppp",
    // بغل تایتل مینویسه
    template: "%s | Hana Shop",
  },
  description: "Generated by create next app",
};

function page() {
  return (
    <div>
       555
    </div>
  )
}

export default page
